spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/photoalbum
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10000KB
      max-request-size: 10000KB

logging:
  level:
    org.hibernate.SQL: debug